import "@/app/styles/globals.scss";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";

const pokeFont = localFont({ src: "pokemon-font.ttf" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={pokeFont.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
